version: '3.8'

services:
  backend:
    container_name: cookiegram-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: cookiegram-backend
    ports:
      - "8080:8080"
    networks:
      - cookiegram-net
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod 

  frontend:
    container_name: cookiegram-frontend
    build:
      context: ./cookiegram-frontend
      dockerfile: Dockerfile
    image: cookiegram-frontend
    ports:
      - "4200:80"   # Browser → NGINX
    depends_on:
      - backend
    networks:
      - cookiegram-net
    restart: unless-stopped

networks:
  cookiegram-net:
    driver: bridge
