package com.group2.backend.payloads;

import lombok.Data;

import java.math.BigDecimal;

@Data
public class PaymentRequest {
    private String paymentMethodId;
    private String currency;
    private BigDecimal amount;
    private String description;
    private String customerEmail;
    private String customerName;
    private String successUrl;
    private String cancelUrl;
    
    // Getters and setters are automatically generated by Lombok @Data
}
